### ISSUE TITLE
Documentation/Examples for ASL2

### ISSUE THREAD

**Issue by whart222** [ampl/asl#12]
Are there worked examples using ASL2?  I'm trying to use EvalWorkspace objects, and I'm seeing unexpected failures to read problems.  But I don't see any worked examples in the documentation to guess where I might be going wrong.

**Comment by glebbelov** [comment]
@whart222 ASL2 was created on request of Knitro and their driver uses it. We have Kntro source code but it is private. I could not find usage of EvalWorkspace in any other drivers, although some use ASL2, e.g., SNOPT, xpress, cplexasl. Their source is public, see https://netlib.org/ampl/solvers/. Probably, all or almost all of the netlib driver examples, except gurobi, work with both ASL and ASL2.  It's just a matter of using the right -I option when compiling and linking against the right libraries. 

Also, asl/src/examples/et.c uses it. This seems to be a library testing program. This might be a good place to start,  otherwise come with questions, and we can look into Knitro's ASL usage, etc.
